server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BajriX
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true